name: nixis
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numba>=0.57
  - numpy>=1.21.4
  - scipy>=1.7.2
  - meshzoo>=0.7.3
  - meshio>=4.4.6
  - pyvista>=0.32.1
  - matplotlib>=3.4.2
  - cmocean>=2
  - pillow>=8.3.2
